#!/bin/dash
atualizar='\033[1;32m'
echo "$atualizar Atualizando repositório..."
apt update && upgrade -y
apt install -y wget python git 
clear
k='\033[01;32m'
echo "\033[1;33m"
echo "                        _    "
echo "  _ __   __ _ _ __ ___ | | __ "
echo " |  _ \ / _  |  __/ _ \| |/ / "
echo " | | | | (_| | | | (_) |   < "
echo " |_| |_|\__, |_|  \___/|_|\_\ "
echo "        |___/ "
echo "		 ___           _        _ _ "
echo "		|_ _|_ __  ___| |_ __ _| | | "
echo "		 | ||  _ \/ __| __/ _  | | | "
echo "		 | || | | \__ \ || (_| | | | "
echo "		|___|_| |_|___/\__\__,_|_|_| "
echo
echo "Deseja instalar o Ngrok? [Y/n]"
read opcao
case $opcao in
y)
echo
echo "Downloading Termux-ngrok..."
case `dpkg --print-architecture` in
aarch64)
    architectureURL="arm64" ;;
arm)
    architectureURL="arm" ;;
armhf)
    architectureURL="armhf" ;;
amd64)
    architectureURL="amd64" ;;
i*86)
    architectureURL="i386" ;;
x86_64)
    architectureURL="amd64" ;;
*)
    echo "Arquitetura desconhecida"
esac


wget "https://github.com/tchelospy/NgrokTest/blob/master/ngrok-stable-linux-${architectureURL}.zip?raw=true" -O ngrok.zip
unzip ngrok.zip
cat ngrok > /data/data/com.termux/files/usr/bin/ngrok
chmod 700 /data/data/com.termux/files/usr/bin/ngrok
rm ngrok ngrok.zip
clear
echo "[+] Ngrok Instalado com susseso!"
echo "[+] Exemplo de comando (ngrok http 80\nOu ngrok para ajuda)"
;;

n)
clear
echo "Ngrok não instalado :("
echo
esac


